### ISSUE TITLE
This gem have intent to support "who's on call" api ?

### ISSUE THREAD

**Issue by jmherbst** [envato/pagerduty#33]
Hello,

I'm wondering if this API https://developer.pagerduty.com/documentation/rest/users/on_call is in scope for this gem.  If so, is there any intent to add support for this?

Thanks,
Jake

**Comment by orien** [comment]
Hi @jmherbst. This gem targets Pagerduty's [Integrations API](https://developer.pagerduty.com/documentation/integration/events) which provides support for triggering, acknowledging and resolving incidents. The gem is intentionally lightweight to be used in production and production monitoring systems. It is unlikely Pagerduty's Rest API will be supported.
