### ISSUE TITLE
PagerDuty#get_incident returns an incident instead of nil when the incident_key is missing

### ISSUE THREAD

**Issue by KevinBongart** [envato/pagerduty#39]
Just noticed that when calling `PagerDuty#get_incident` with `nil` as `incident_key`, I get an incident object with an empty `incident_key`:

```ruby
irb(main):015:0> client
=> #<Pagerduty:0x007febcb9f79c8 @service_key="xxxxxx">
irb(main):016:0> client.get_incident(nil)
=> #<PagerdutyIncident:0x007febcb986318 @service_key="xxxxxx", @incident_key=nil>
irb(main):017:0> client.get_incident(nil).present?
=> true
```

Is this intended? In my opinion this is dangerous behavior that could lead to errors. What do you think about raising an error when the key is missing?

**Comment by joneslee85** [comment]
@KevinBongart I don't think it is intended. PR welcome
