### ISSUE TITLE
Is this maintained?

### ISSUE THREAD

**Issue by jaxxstorm** [envato/pagerduty#42]
I'm trying to figure out the best way to update the sensu-plugin for pagerduty with a library that's actively maintained:

https://github.com/sensu-plugins/sensu-plugins-pagerduty/issues/10

Currently it's using [portertech/redphone](https://github.com/portertech/redphone) but it seems unmaintained and I'd like to add support for urgencies to this library

**Comment by joneslee85** [comment]
cc @orien

**Comment by orien** [comment]
Hi @jaxxstorm. This project is maintained. Envato uses it in production and needs it to work. The Pagerduty integration API changes infrequently so there has been minimal work done on this gem recently.
