### ISSUE TITLE
Does it support PagerDuty's v2 Api?

### ISSUE THREAD

**Issue by sternr** [envato/pagerduty#49]
Hey,

As PD announced v1 is deprecated and going to die soon, does the sensu-plugin support the v2 api?
Thanks!

**Comment by orien** [comment]
Hi @sternr,

This gem integrates with the PagerDuty Events API (V1). As PagerDuty has only deprecated their Rest API V1, this gem is not affected.

https://v2.developer.pagerduty.com/v2/docs/api-v2-frequently-asked-questions#section-what-will-happen-to-integrations-
> WHAT WILL HAPPEN TO INTEGRATIONS?
Most integrations, which use the Events API (v1) as distinct from the REST API (v1), will not be affected. Support will end only for the v1 REST API, and not for the Events API.
