### ISSUE TITLE
Events API v2 support?

### ISSUE THREAD

**Issue by hngl** [envato/pagerduty#61]
How do you feel about supporting the [Events API v2](https://v2.developer.pagerduty.com/docs/send-an-event-events-api-v2)? 

The _Event API v2_ supports setting "Severity", which in turn allows for the "Urgency by Severity" escalation configuration.

There is the branch [`api-2`](https://github.com/envato/pagerduty/tree/api-2) in the repo. What do you need to get it to a release?

**Comment by hngl** [comment]
@reidcooper Is branch `api-2` still active?

**Comment by reidcooper** [comment]
@hngl You are welcome to use the branch, https://github.com/envato/pagerduty/pull/52

I am not going to actively maintain the branch. The primary reason why I decided to start the branch was for the same reason - "severity". As I used the branch at my last company, I don't need it anymore. You are more than welcome to follow up with it. I believe the maintainers were interested in using it but not sure what the status is.

**Comment by johnsyweb** [comment]
Thanks for opening this issue. We'll take a look into the effort required and assess where this sits with our existing priorities.

**Comment by orien** [comment]
I think we should provide backwards compatibility as some Pagerduty service configurations don't support the Events API V2. Giving the option to use V1 or V2 would be ideal.

I'll look into how we might do this.

**Comment by orien** [comment]
To support both V1 and V2 we'll need a small change in the interface.

I've put forth a proposal in #64.

**Comment by orien** [comment]
An implementation of Events API v2 is now on `master`.
