### ISSUE TITLE
Example request raises 400 error - Length of 'routing_key' is incorrect

### ISSUE THREAD

**Issue by adsteel** [envato/pagerduty#70]
Given I have generated a pagerduty API key with full access
And I follow the example in the readme
Then I should see an event in pagerduty

Instead:

```ruby
> pagerduty = Pagerduty.build(
*  integration_key: ENV.fetch('PAGERDUTY_INTEGRATION_KEY'),
*  api_version: 2
*)
> pagerduty.trigger(
*  summary:  "summary",
*  source:   "source",
*  severity: "critical"
)
Net::HTTPServerException: 400 "Bad Request"
from /home/adsteel/.asdf/installs/ruby/2.6.6/lib/ruby/2.6.0/net/http/response.rb:122:in `error!'
```

This may be me missing something, but I figured I'd at least record my struggle for anyone else who runs into this.

**Comment by adsteel** [comment]
Okay, following the readme at the bottom shows me how to get better info:

```ruby
begin
  pagerduty.trigger(
    summary:  "summary",
    source:   "source",
    severity: "critical"
  )
rescue Net::HTTPServerException => error
  puts error.response.code
  puts error.response.message
  puts error.response.body
end

400
Bad Request
{"status":"invalid event","message":"Event object is invalid","errors":["Length of 'routing_key' is incorrect (should be 32 characters)"]}
```

Not sure what the routing_key is, but I regenerated my API key and both the old and new were only 20 characters.

**Comment by orien** [comment]
Hi @adsteel, PageDuty offers two APIs, an Events API and a Rest API. This gem integrates with the Events API, so you'll need to get a PagerDuty Events API specific token.

PagerDuty has some instructions for this here https://support.pagerduty.com/docs/services-and-integrations#create-a-generic-events-api-integration

**Comment by adsteel** [comment]
@orien that was it, thanks so much!
